--[[
    RmCurveInjector.lua

    PHASE 1 -- Animal-IO curve injector (engine glue).

    Some animal subTypes have no `input.straw` / `output.manure` AnimCurve, so
    nothing reads them and no manure is produced (intake and production stay 0).
    This module supplies the two missing curves at runtime. Which subTypes lack them
    is NOT assumed or hardcoded -- it is decided per subType from the runtime data.
    (In the base game chicken and the sheep/goat subTypes lack them while cow/pig/horse
    define them, but a map or mod may add types/subTypes, drop curves, or define
    straw/manure on any subType -- so we never take any subType's curves for granted.)

    At `loadMapFinished`, iterate the FLAT `g_currentMission.animalSystem.subTypes`
    list (which includes every map/mod-added type/subType, rebuilt each load); for
    each subType that HAS a non-empty `input.food` but LACKS `input.straw` and/or
    `output.manure`, build a new AnimCurve by cloning the food curve's keyframes
    (shape-agnostic -- maps/mods rewrite food) with each value scaled by a per-subType
    ratio K (from RmManureRatios), normalizing a single-keyframe source to a get()-safe
    flat 2-keyframe curve, and assign it. Inject ONLY where nil -- idempotent; any
    subType that already defines a curve (base cow/pig/horse today, or anything a
    map/mod defines, e.g. RealisticLivestock) is left untouched.

    Runs on ALL peers (never server-gated): subType curve data is built locally and
    is never streamed. Deterministic per peer (identical mod set, hardcoded K,
    identical food curves), so no sync event.

    Scope: Phase 1 delivers curve PRESENCE + VALUE only. These curves are inert
    until a later slice attaches the straw spec and a straw source; zero production
    from Phase 1 alone is EXPECTED.

    The pure ratio tables + `scaledKeyframes`/`kForSubType` live in
    core/RmManureRatios.lua; this module is the in-game glue over AnimCurve /
    g_currentMission.animalSystem. Console registration belongs to the slice-0
    console shell (RmManureConsole), which delegates `mfaDump curves` here.

    Author: Ritter
]]

-- Module table doubles as the install-guard home (the loadMapFinished hook is
-- installed exactly once via RmCurveInjector.installed).
RmCurveInjector = RmCurveInjector or {}

local Log = RmLogging.getLogger("ManureForAll")

-- ============================================================================
-- ENGINE GLUE (in-game only -- touches AnimCurve / g_currentMission.animalSystem)
-- ============================================================================

---Build a new scaled AnimCurve from a source curve. Thin wrapper over the pure
--- function: constructs `AnimCurve.new(linearInterpolator1)` (degree defaults to 2)
--- and adds each scaled keyframe.
---@param sourceCurve AnimCurve the source curve with a `.keyframes` list (the food curve)
---@param k number scale factor
---@return AnimCurve curve a new AnimCurve with >= 2 keyframes
local function buildScaledCurve(sourceCurve, k)
    -- @as cast: the autogenerated AnimCurve.new stub lacks a @return, so the LSP
    -- infers nil; the cast documents that new() yields an AnimCurve.
    local curve = AnimCurve.new(linearInterpolator1) --[[@as AnimCurve]]
    local kfs = RmManureRatios.scaledKeyframes(sourceCurve.keyframes, k)
    for i = 1, #kfs do
        curve:addKeyframe(kfs[i])
    end
    return curve
end

---Inject the missing straw/manure curves on every eligible subType.
--- Runs on EVERY `loadMapFinished` against that load's fresh `subTypes` table and
--- re-guards per-subType with `== nil` (curves are runtime-only and rebuilt each
--- load). Guards the system, iterates the flat subType list, skips malformed and
--- foodless subTypes, resolves K strictly via `subType.typeIndex`, and injects
--- only where the target curve is nil.
function RmCurveInjector.injectAll()
    Log:trace(">>> injectAll()")

    local animalSystem = g_currentMission and g_currentMission.animalSystem
    if animalSystem == nil then
        Log:trace("<<< injectAll = nil (no animalSystem)")
        return
    end

    local injected, skippedExisting, skippedNoFood, skippedEmptyFood = 0, 0, 0, 0

    for _, subType in ipairs(animalSystem.subTypes) do
        if subType.input ~= nil and subType.output ~= nil then
            local food = subType.input.food
            if food == nil then
                skippedNoFood = skippedNoFood + 1
                Log:debug("SKIP-NO-FOOD: subType '%s' has no input.food", tostring(subType.name))
            elseif food.numKeyframes < 1 then
                skippedEmptyFood = skippedEmptyFood + 1
                Log:debug("SKIP-EMPTY-FOOD: subType '%s' input.food has 0 keyframes", tostring(subType.name))
            else
                local t = animalSystem:getTypeByIndex(subType.typeIndex)
                local typeName = t and t.name
                local k = RmManureRatios.kForSubType(subType.name, typeName)
                -- Derive "used fallback" from the single source of truth: kForSubType
                -- returns K_FALLBACK (by table identity) exactly when neither the
                -- subType nor the type matched, so this log can never drift from the K
                -- actually applied.
                if k == RmManureRatios.K_FALLBACK then
                    Log:debug("K-FALLBACK: subType '%s' (type '%s') matched no subType/type K; using fallback",
                        tostring(subType.name), tostring(typeName))
                end

                local didInject = false
                if subType.input.straw == nil then
                    subType.input.straw = buildScaledCurve(food, k.straw)
                    didInject = true
                end
                if subType.output.manure == nil then
                    subType.output.manure = buildScaledCurve(food, k.manure)
                    didInject = true
                end

                if didInject then
                    injected = injected + 1
                    Log:debug("INJECT: subType '%s' (type '%s') straw K=%.3f manure K=%.3f (food kf=%d)",
                        tostring(subType.name), tostring(typeName), k.straw, k.manure, food.numKeyframes)
                else
                    skippedExisting = skippedExisting + 1
                    Log:debug("SKIP-EXISTING: subType '%s' already has straw and manure", tostring(subType.name))
                end
            end
        else
            Log:debug("SKIP-MALFORMED: subType '%s' has nil input/output", tostring(subType and subType.name))
        end
    end

    -- Record this load's outcome so the no-argument `mfaDump curves` summary can
    -- report what Phase 1 ACTUALLY injected (not merely which subTypes currently have
    -- both curves, which would also count pre-existing cow/pig/horse and RL animals).
    RmCurveInjector.lastRun = {
        injected = injected,
        skippedExisting = skippedExisting,
        skippedNoFood = skippedNoFood,
        skippedEmptyFood = skippedEmptyFood,
    }

    Log:info("Phase 1 curve injection: injected=%d, skipped-existing=%d, skipped-no-food=%d, skipped-empty-food=%d",
        injected, skippedExisting, skippedNoFood, skippedEmptyFood)
    Log:trace("<<< injectAll")
end

---Hook body appended to `BaseMission.loadMapFinished` -- runs injection every load.
local function onLoadMapFinished()
    RmCurveInjector.injectAll()
end

-- ============================================================================
-- DUMP (delegated from the console shell: `mfaDump curves [name]`)
--
-- In-game verification. Matches by subType-name OR type-name (case-folded), so
-- `chicken`/`CHICKEN` both report the CHICKEN subType AND CHICKEN_ROOSTER. Reports
-- numKeyframes, curve identity (tostring), and sampled value vs food*K at a keyframe
-- age (plus a second age beyond maxTime for flat/normalized curves).
-- Mission/animalSystem-nil guarded.
-- ============================================================================

---Sample a curve safely for reporting. Avoids the single-keyframe get() hazard
--- (sampling a 1-kf curve via get() is unsafe) by returning the raw keyframe
--- value for a 1-kf curve -- so dumping the flagship chicken's
--- single-keyframe FOOD curve never crashes this verification tool. The injected
--- straw/manure curves are always >= 2 kf and sample via get().
local function sampleCurve(curve, time)
    if curve == nil or curve.numKeyframes == nil or curve.numKeyframes < 1 then
        return nil
    end
    if curve.numKeyframes == 1 then
        return curve.keyframes[1][1]
    end
    return curve:get(time)
end

---Dump one subType's straw/manure curves against its food curve.
local function dumpSubType(animalSystem, subType)
    local t = animalSystem:getTypeByIndex(subType.typeIndex)
    local typeName = t and t.name
    local k = RmManureRatios.kForSubType(subType.name, typeName)
    local food = subType.input and subType.input.food
    local straw = subType.input and subType.input.straw
    local manure = subType.output and subType.output.manure

    local foodKf = food and food.numKeyframes or 0
    local ageLow = 0
    local ageKey = (food ~= nil and foodKf >= 1 and food.keyframes[1].time) or 0
    local ageHigh = (food ~= nil and (food.maxTime or ageKey) + 12) or 12

    Log:info("DUMP subType '%s' (type '%s'): food kf=%d, straw=%s (kf=%s), manure=%s (kf=%s)",
        tostring(subType.name), tostring(typeName), foodKf,
        tostring(straw), tostring(straw and straw.numKeyframes),
        tostring(manure), tostring(manure and manure.numKeyframes))

    if food ~= nil and foodKf >= 1 then
        for _, age in ipairs({ ageLow, ageKey, ageHigh }) do
            local f = sampleCurve(food, age)
            local s = sampleCurve(straw, age)
            local m = sampleCurve(manure, age)
            Log:info("  age=%s: food=%s straw=%s (food*K_straw=%s) manure=%s (food*K_manure=%s)",
                tostring(age), tostring(f),
                tostring(s), tostring(f and f * k.straw),
                tostring(m), tostring(f and f * k.manure))
        end
    end
end

---Dump handler for `mfaDump curves [name]`, called by the console dispatcher.
--- No name -> the last-run injection summary (from injectAll's recorded counters);
--- a name -> per-subType dumps for the case-insensitive subType-or-type match.
---@param nameArg string|nil optional subType-name OR type-name (case-insensitive)
---@return string message console-return string (mfaDump curves-prefixed)
function RmCurveInjector.dumpCurves(nameArg)
    local mission = g_currentMission
    local animalSystem = mission and mission.animalSystem
    if animalSystem == nil then
        return "mfaDump curves: no mission/animalSystem yet -- load a save first"
    end

    if nameArg == nil or nameArg == "" then
        -- Report what Phase 1 ACTUALLY injected on the last load (from injectAll's
        -- recorded counters), not merely which subTypes currently have both curves --
        -- the latter would also count pre-existing cow/pig/horse and RL animals and
        -- so could not tell "we injected these" from "these were already present".
        local r = RmCurveInjector.lastRun
        if r == nil then
            return "mfaDump curves: injectAll has not run yet this load (pass a name to dump a subType)"
        end
        return string.format(
            "mfaDump curves: last injection -- injected=%d, skipped-existing=%d, skipped-no-food=%d, skipped-empty-food=%d (pass a name to dump one)",
            r.injected, r.skippedExisting, r.skippedNoFood, r.skippedEmptyFood)
    end

    local want = string.upper(nameArg)
    local matched = 0
    for _, subType in ipairs(animalSystem.subTypes) do
        local t = animalSystem:getTypeByIndex(subType.typeIndex)
        local typeName = t and t.name
        local subName = subType.name
        if (subName ~= nil and string.upper(subName) == want)
            or (typeName ~= nil and string.upper(typeName) == want) then
            matched = matched + 1
            dumpSubType(animalSystem, subType)
        end
    end

    if matched == 0 then
        return string.format("mfaDump curves: no subType/type matches '%s'", nameArg)
    end
    return string.format("mfaDump curves: dumped %d subType(s) matching '%s' (see log)", matched, nameArg)
end

-- ============================================================================
-- INSTALL (guarded loadMapFinished self-install only)
--
-- Two distinct guards -- do NOT conflate:
--  (a) the loadMapFinished HOOK is installed exactly once via this module-table
--      field so re-sourcing cannot double-hook;
--  (b) injectAll runs on EVERY loadMapFinished and re-guards per-subType with
--      == nil. Injection is NEVER gated on a first-run/savegame flag -- curves are
--      runtime-only and MUST be rebuilt on every load (return-to-menu, client join).
--
-- Console-command registration is NOT done here: it belongs to the slice-0 console
-- shell (RmManureConsole), which delegates `mfaDump curves` to dumpCurves above.
-- ============================================================================

if not RmCurveInjector.installed then
    BaseMission.loadMapFinished = Utils.appendedFunction(BaseMission.loadMapFinished, onLoadMapFinished)
    RmCurveInjector.installed = true
end
